//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlytaloMvc
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaunanTila
    {
        public int SaunanTilaId { get; set; }
        public int SaunaId { get; set; }
        public Nullable<bool> SaunaOnOff { get; set; }
        public Nullable<decimal> SaunanPerusLämpö { get; set; }
    
        public virtual Saunat Saunat { get; set; }
    }
}
