//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlytaloMvc
{
    using System;
    using System.Collections.Generic;
    
    public partial class TalonLämpö
    {
        public int TalonLämpöId { get; set; }
        public int TaloId { get; set; }
        public Nullable<int> TalonNykyLämpö { get; set; }
        public Nullable<int> TalonTavoiteLämpö { get; set; }
    
        public virtual Talot Talot { get; set; }
    }
}
