//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlytaloMvc
{
    using System;
    using System.Collections.Generic;
    
    public partial class ValonTila
    {
        public int ValonTilaId { get; set; }
        public int HuoneId { get; set; }
        public int ValoId { get; set; }
        public bool ValoOnOff { get; set; }
        public Nullable<decimal> ValonMaara { get; set; }
    
        public virtual Huoneet Huoneet { get; set; }
        public virtual Valot Valot { get; set; }
    }
}
